# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit, manual]

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: [
          "@commitlint/config-conventional",
          "conventional-changelog-conventionalcommits"
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: check-yaml
        args: ['--unsafe']
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.1.3
    hooks:
      - id: ansible-lint
        always_run: false
        pass_filenames: true
        entry: env ansible-lint
        files: \.(yaml|yml)$
        exclude: venv|molecule|\.pre-commit-config\.yaml|\.github
