---
driver:
  name: molecule_hetznercloud
platforms:
  - name: teku-ubuntu24
    server_type: cx22 # 2cpu/4ram intel shared
    image: ubuntu-24.04
scenario:
  test_sequence:
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  options:
    D: true
verifier:
  name: testinfra
  options:
    verbose: true
  env:
    PYTEST_ADDOPTS: --color=yes -s
lint: |
  set -e
  yamllint .
  ansible-lint .
