name: Teku molecule test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  molecule-test:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.8'

      - name: Install system dependencies for Java
        run: |
          sudo apt-get update
          sudo apt-get install -y libjna-java libc6 libstdc++6 zlib1g libnss3 openjdk-21-jre-headless

      - name: Initialize environment
        run: |
          make init

      - name: Run Molecule tests
        run: |
          molecule --version
          molecule -v test
